swagger: '2.0'
info:
  description: 第一个
  version: 1.0.0
  title: 新建文档
schemes:
  - https
paths:
  /api/get:
    get:
      summary: get方法
      description: 子服务：com.qunhe.service.hello;<br> 这里是get方法
      responses:
       200:
          description: undefined
          schema:
            type: string
            example: 成功
      parameters:
      - name: num
        in: query
        description: undefined
        type: number
        required: true
